---
site_name: Recipes
site_description: A collection of my recipes.
site_author: Nicholas Wilde
site_url: https://nicholaswilde.io/recipes
copyright: Copyright &copy; 2022 Nicholas Wilde
dev_addr: '0.0.0.0:8000'

repo_url: https://github.com/nicholaswilde/recipes
repo_name: nicholaswilde/recipes
edit_uri: "edit/main/docs/"

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
    logo: fontawesome/solid/bowl-rice
  favicon: assets/images/favicon.svg
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.tracking
    #  - navigation.expand
    - navigation.top

nav:
  - Home: index.md
  - Asian:
      - Coconut Curried Vegetables with Rice: asian/coconut-curried-vegetables-with-rice.md
      - Cool and Spicy Noodle Salad: asian/cool-and-spicy-noodle-salad.md
      - Crispy Peanut Tofu & Cauliflower Rice Stir Fry: asian/crispy-peanut-tofu-&-cauliflower-rice-stir-fry.md
      - Everyday Chinese Vegetable Stir-Fry: asian/everyday-chinese-vegetable-stir-fry.md
      - Noodle-Free Pad Thai: asian/noodle-free-pad-thai.md
      - Simple Fried Rice: asian/simple-fried-rice.md
  - Beverages:
      - Iced Chai Latte: beverages/iced-chai-latte.md
      - Old Irish Coffee: beverages/old-irish-coffee.md
      - Olde Tyme Lemonade: beverages/olde-tyme-lemonade.md
      - Pineapple Paradise: beverages/pineapple-paradise.md
  - Breads:
      - Best-Ever Banana Bread: breads/best-ever-banana-bread.md
      - Bread Machine French Bread: breads/bread-machine-french-bread.md
      - Chocolate Chip Peanut Butter Banana Bread: breads/chocolate-chip-peanut-butter-banana-bread.md
      - Cranberry Orange Bread: breads/cranberry-orange-bread.md
      - Croissants: breads/croissants.md
      - Honey Beer Bread: breads/honey-beer-bread.md
      - Honey Cornbread: breads/honey-cornbread.md
      - Lemon Blueberry Bread: breads/lemon-blueberry-bread.md
      - Parmesan Pull-Apart Bread: breads/parmesan-pull-apart-bread.md
  - Breakfast:
      - 1-Bowl Carrot Apple Muffins: breakfast/1-bowl-carrot-apple-muffins.md
      - Apple Pie Overnight Oats: breakfast/apple-pie-overnight-oats.md
      - Breakfast Potatoes: breakfast/breakfast-potatoes.md
      - Buttermilk Whole Wheat Waffles: breakfast/buttermilk-whole-wheat-waffles.md
      - Decadent Chocolate Overnight Oats: breakfast/decadent-chocolate-overnight-oats.md
      - French Toast: breakfast/french-toast.md
      - Gordon Ramsay Scrambled Eggs: breakfast/gordon-ramsay-scrambled-eggs.md
      - Joy of Cooking Pancakes: breakfast/joy-of-cooking-pancakes.md
      - Peanut Butter Overnight Oats: breakfast/peanut-butter-overnight-oats.md
      - The Food Lab Light and Fluffy Scrambled Eggs: breakfast/the-food-lab-light-and-fluffy-scrambled-eggs.md
      - Zeb's Waffles: breakfast/zeb's-waffles.md
  - Desserts:
      - 1-Bowl Vegan Gluten-Free Carrot Cake: desserts/1-bowl-vegan-gluten-free-carrot-cake.md
      - 4 Ingredient Chocolate Mousse: desserts/4-ingredient-chocolate-mousse.md
      - Apple Cinnamon Raisin Bars: desserts/apple-cinnamon-raisin-bars.md
      - Blueberry Pie: desserts/blueberry-pie.md
      - Browned Butter Blondies: desserts/browned-butter-blondies.md
      - Butterfinger Ice Cream Pie: desserts/butterfinger-ice-cream-pie.md
      - Buttery Shortbread: desserts/buttery-shortbread.md
      - Chewy Brownies: desserts/chewy-brownies.md
      - Chewy Peanut Butter Cookies: desserts/chewy-peanut-butter-cookies.md
      - Choco Taco: desserts/choco-taco.md
      - Chocolate Scotcheroos: desserts/chocolate-scotcheroos.md
      - Cinnamon Coffee Cake: desserts/cinnamon-coffee-cake.md
      - Consumer Union Chocolate Chip Cookies: desserts/consumer-union-chocolate-chip-cookies.md
      - Cook’s Illustrated Perfect Chocolate Chip Cookies: desserts/cook’s-illustrated-perfect-chocolate-chip-cookies.md
      - Corn & Hatch Chile Cupcakes with Honey Buttercream: desserts/corn-&-hatch-chile-cupcakes-with-honey-buttercream.md
      - Crème Pâtissière: desserts/crème-pâtissière.md
      - Disney's Churros: desserts/disney's-churros.md
      - Disney's Frozen Pineapple Treat: desserts/disney's-frozen-pineapple-treat.md
      - French Fruit Tart: desserts/french-fruit-tart.md
      - Glazed Lemon Bars: desserts/glazed-lemon-bars.md
      - Lemon Pie: desserts/lemon-pie.md
      - Melomakarona: desserts/melomakarona.md
      - Millionaire's Shortbread: desserts/millionaire's-shortbread.md
      - No-Bake Banana and Peanut Butter Caramel Icebox Cake: desserts/no-bake-banana-and-peanut-butter-caramel-icebox-cake.md
      - Oatmeal Chocolate Chip Cookies: desserts/oatmeal-chocolate-chip-cookies.md
      - Olive Oil Cake: desserts/olive-oil-cake.md
      - Peanut Butter Crisscrosses: desserts/peanut-butter-crisscrosses.md
      - Peanut Butter Cups: desserts/peanut-butter-cups.md
      - Peanut Butter Sandwich Cookies: desserts/peanut-butter-sandwich-cookies.md
      - Pineapple Upside Down Cake: desserts/pineapple-upside-down-cake.md
      - Preposterously Peanut Butter Cup Cookies: desserts/preposterously-peanut-butter-cup-cookies.md
      - Simple Sugar Cookies: desserts/simple-sugar-cookies.md
      - Slow Cooker Apple Crisp: desserts/slow-cooker-apple-crisp.md
      - Strawberry Mousse: desserts/strawberry-mousse.md
      - Strawberry Shortcakes: desserts/strawberry-shortcakes.md
      - The New York Times Chocolate Chip Cookies: desserts/the-new-york-times-chocolate-chip-cookies.md
      - Tollhouse Pie: desserts/tollhouse-pie.md
      - Trader Joe's Key Lime Pie with Strawberry Whipped Cream: desserts/trader-joe's-key-lime-pie-with-strawberry-whipped-cream.md
      - Vegan Chocolate Pudding with Cinnamon and Chile: desserts/vegan-chocolate-pudding-with-cinnamon-and-chile.md
      - Vegan Strawberry Cake: desserts/vegan-strawberry-cake.md
      - World's Best Brownies: desserts/world's-best-brownies.md
  - Ingredients:
      - Brown Sugar: ingredients/brown-sugar.md
      - Buttermilk: ingredients/buttermilk.md
      - Cinnamon Sugar: ingredients/cinnamon-sugar.md
      - Crème Fraîche: ingredients/crème-fraîche.md
      - Danish Pastry Dough: ingredients/danish-pastry-dough.md
      - Flavored Sugars: ingredients/flavored-sugars.md
      - Pâte à Choux: ingredients/pâte-à-choux.md
      - Peanut Butter: ingredients/peanut-butter.md
      - Puff Pastry: ingredients/puff-pastry.md
      - Ranch Dressing Mix: ingredients/ranch-dressing-mix.md
      - Ricotta: ingredients/ricotta.md
      - Sourdough Starter: ingredients/sourdough-starter.md
      - Sweet Pastry: ingredients/sweet-pastry.md
      - Taco Seasoning: ingredients/taco-seasoning.md
      - Yogurt: ingredients/yogurt.md
  - Italian:
      - Baked Cream Cheese Spaghetti Casserole: italian/baked-cream-cheese-spaghetti-casserole.md
      - Caprese Risoni: italian/caprese-risoni.md
      - Easiest Ever Macaroni & Cheese: italian/easiest-ever-macaroni-&-cheese.md
      - Eggplant Parm Meatballs: italian/eggplant-parm-meatballs.md
      - Eggplant Parmesan Pasta: italian/eggplant-parmesan-pasta.md
      - Ginger Sesame Vegan Meatballs: italian/ginger-sesame-vegan-meatballs.md
      - Healthy Pasta with Pesto and Broccoli: italian/healthy-pasta-with-pesto-and-broccoli.md
      - Light and Tender Potato Gnocchi with Sage Butter Sauce: italian/light-and-tender-potato-gnocchi-with-sage-butter-sauce.md
      - Jamie Oliver Ricotta Fritters: italian/jamie-oliver-ricotta-fritters.md
      - Macaroni & Cheese: italian/macaroni-&-cheese.md
      - Mezza Luna Lasagna: italian/mezza-luna-lasagna.md
      - Olive Garden Fettuccine Alfredo: italian/olive-garden-fettuccine-alfredo.md
      - Pasta with Burst Cherry Tomato Sauce: italian/pasta-with-burst-cherry-tomato-sauce.md
      - Spaghetti All'Assassina: italian/spaghetti-all'assassina.md
      - Spaghetti Alla Puttanesca: italian/spaghetti-alla-puttanesca.md
      - Spinach Lasagna: italian/spinach-lasagna.md
      - Summer Pesto Pasta: italian/summer-pesto-pasta.md
      - Trapani-Style Pasta: italian/trapani-style-pasta.md
  - Lunches:
      - Bourbon Grilled Cheese: lunches/bourbon-grilled-cheese.md
      - Chickpea Sunflower Sandwich: lunches/chickpea-sunflower-sandwich.md
      - Perfect Chickpea Salad: lunches/perfect-chickpea-salad.md
      - Vegan Caesar Salad: lunches/vegan-caesar-salad.md
  - Main:
      - Baked Sweet Potatoes With Chili Beans: main/baked-sweet-potatoes-with-chili-beans.md
      - Cabbage and Sun-Dried Tomato Sauté: main/cabbage-and-sun-dried-tomato-sauté.md
      - Cowboy Quinoa Bake: main/cowboy-quinoa-bake.md
      - Crispy Chicken-less Sliders: main/crispy-chicken-less-sliders.md
      - Fall Turkey Chili With Pumpkin: main/fall-turkey-chili-with-pumpkin.md
      - Fresh Fava Beans with Mint and Scallions: main/fresh-fava-beans-with-mint-and-scallions.md
      - Peruvian Burrito Bowl: main/peruvian-burrito-bowl.md
      - Spicy Pumpkin Curry Pot Pie: main/spicy-pumpkin-curry-pot-pie.md
  - Mediterranean:
      - Baked Feta with Chickpeas and Kale: mediterranean/baked-feta-with-chickpeas-and-kale.md
      - Balsamic Lentil Sauté: mediterranean/balsamic-lentil-sauté.md
      - Cook's Illustrated Horiatiki Salata (Greek Salad): mediterranean/cook's-illustrated-horiatiki-salata-(greek-salad).md
      - Gordon Ramsay's Spicy Sausage Rice: mediterranean/gordon-ramsay's-spicy-sausage-rice.md
      - Greek Orzo Stuffed Red Peppers: mediterranean/greek-orzo-stuffed-red-peppers.md
      - Harissa Olive Oil-Braised Chickpeas and Fennel: mediterranean/harissa-olive-oil-braised-chickpeas-and-fennel.md
      - Jeanie's Falafel: mediterranean/jeanie's-falafel.md
      - Lemon Garlic Orzo with Roasted Veggies: mediterranean/lemon-garlic-orzo-with-roasted-veggies.md
      - Mediterranean-Inspired Orzo Pasta Salad: mediterranean/mediterranean-inspired-orzo-pasta-salad.md
      - Mediterranean Pasta Salad: mediterranean/mediterranean-pasta-salad.md
      - Saucy Moroccan-Spiced Lentils: mediterranean/saucy-moroccan-spiced-lentils.md
      - Scrambled Chickpea and Spinach Pitas: mediterranean/scrambled-chickpea-and-spinach-pitas.md
      - Sprouted Kitchen Spring Noodles Artichokes and Lemons: mediterranean/sprouted-kitchen-spring-noodles-artichokes-and-lemons.md
      - Tomato Baked White Beans with Lemon Parsley Oil: mediterranean/tomato-baked-white-beans-with-lemon-parsley-oil.md
      - Vegetarian Paella: mediterranean/vegetarian-paella.md
  - Mexican:
      - Black Bean Burritos: mexican/black-bean-burritos.md
      - Black Bean Burrito Bake: mexican/black-bean-burrito-bake.md
      - Butternut Squash Tostadas: mexican/butternut-squash-tostadas.md
      - Cheesy Black Bean Quesadilla Triangles: mexican/cheesy-black-bean-quesadilla-triangles.md
      - Chipotle Breakfast Tacos: mexican/chipotle-breakfast-tacos.md
      - Chipotle-Inspired Vegan Burrito Bowls: mexican/chipotle-inspired-vegan-burrito-bowls.md
      - Lentil Fajita Tacos with Zhoug Crema: mexican/lentil-fajita-tacos-with-zhoug-crema.md
      - Mexican Garbanzo Salad: mexican/mexican-garbanzo-salad.md
      - Potato Tacos: mexican/potato-tacos.md
      - Slow Cooker Black Bean Chili: mexican/slow-cooker-black-bean-chili.md
      - Sweet and Spicy Corncakes: mexican/sweet-and-spicy-corncakes.md
      - Taco Bake: mexican/taco-bake.md
      - Taquito-lada Casserole: mexican/taquito-lada-casserole.md
      - Tofu Tacos: mexican/tofu-tacos.md
  - Pressure Cooker:
      - Black Beans: pressurecooker/black-beans.md
      - Chickpeas: pressurecooker/chickpeas.md
  - Sauces & Dressings:
      - A Very Popular BBQ Sauce: sauces-and-dressings/a-very-popular-bbq-sauce.md
      - Aji Verde: sauces-and-dressings/aji-verde.md
      - Blue Cheese Herb Spread: sauces-and-dressings/blue-cheese-herb-spread.md
      - Carrot-Tamarind Chutney : sauces-and-dressings/carrot-tamarind-chutney.md
      - Cashew Chipotle Ranch Dressing: sauces-and-dressings/cashew-chipotle-ranch-dressing.md
      - Classic Mustard: sauces-and-dressings/classic-mustard.md
      - Classic Tartar Sauce: sauces-and-dressings/classic-tartar-sauce.md
      - Cook's Country Perfect Pesto: sauces-and-dressings/cook's-country-perfect-pesto.md
      - Hummus: sauces-and-dressings/hummus.md
      - Lemon-Pepper Parsley Pesto: sauces-and-dressings/lemon-pepper-parsley-pesto.md
      - Mayonnaise: sauces-and-dressings/mayonnaise.md
      - Mexicrema Dressing: sauces-and-dressings/mexicrema-dressing.md
      - New York Times' Classic Marinara Sauce: sauces-and-dressings/new-york-times'-classic-marinara-sauce.md
      - Ranch Dip: sauces-and-dressings/ranch-dip.md
      - Ranch Dressing: sauces-and-dressings/ranch-dressing.md
      - Simple Barbecue Sauce: sauces-and-dressings/simple-barbecue-sauce.md
      - Simple Tartar Sauce: sauces-and-dressings/simple-tartar-sauce.md
      - Spaghetti Sauce: sauces-and-dressings/spaghetti-sauce.md
      - Special Sauce for Burgers: sauces-and-dressings/special-sauce-for-burgers.md
      - Sweet-and-Spicy Ketchup: sauces-and-dressings/sweet-and-spicy-ketchup.md
      - Tahini: sauces-and-dressings/tahini.md
      - Tzatziki Sauce: sauces-and-dressings/tzatziki-sauce.md
      - White Mac and Cheese Sauce: sauces-and-dressings/white-mac-and-cheese-sauce.md
  - Sides:
      - America's Test Kitchen Best Baked Potatoes: sides/america's-test-kitchen-best-baked-potatoes.md
      - America's Test Kitchen Best Baked Sweet Potatoes: sides/america's-test-kitchen-best-baked-sweet-potatoes.md
      - Couscous Feta Salad: sides/couscous-feta-salad.md
      - Eggless Egg Salad: sides/eggless-egg-salad.md
      - Falafel Scones with Harissa Yogurt: sides/falafel-scones-with-harissa-yogurt.md
      - Garlic Rice: sides/garlic-rice.md
      - Golden French Mashed Potatoes: sides/golden-french-mashed-potatoes.md
      - Granola Bars: sides/granola-bars.md
      - Hasselback Roasted Zucchini: sides/hasselback-roasted-zucchini.md
      - Honey Glazed Carrots & Parsnips: sides/honey-glazed-carrots-and-parsnips.md
      - Jalapeño Corn Pudding: sides/jalapeño-corn-pudding.md
      - Jojo's Biscuits: sides/jojo's-biscuits.md
      - Josh Elkin's Mushroom Toast: sides/josh-elkin's-mushroom-toast.md
      - Peanut Butter Bites: sides/peanut-butter-bites.md
      - Pickled Red Onions: sides/pickled-red-onions.md
      - Spicy Garlic Edamame: sides/spicy-garlic-edamame.md
      - The Best Crispy Roast Potatoes Ever Recipe: sides/the-best-crispy-roast-potatoes-ever-recipe.md
      - Unexpected Cheddar Cheese Ball: sides/unexpected-cheddar-cheese-ball.md
  - Soups & Stews:
      - Black Bean and Butternut Soup: soups-and-stews/black-bean-and-butternut-soup.md
      - Chickenless Sausage and Lentil Soup: soups-and-stews/chickenless-sausage-and-lentil-soup.md
      - Chipotle Corn Chowder: soups-and-stews/chipotle-corn-chowder.md
      - Eggplant Stew: soups-and-stews/eggplant-stew.md
      - French Onion Soup: soups-and-stews/french-onion-soup.md
      - Ikarian Longevity Stew: soups-and-stews/ikarian-longevity-stew.md
      - Lemony Lentil Soup: soups-and-stews/lemony-lentil-soup.md
      - Mexican Lentil Soup: soups-and-stews/mexican-lentil-soup.md
      - Plant-Based Chili: soups-and-stews/plant-based-chili.md
      - Roasted Sweet Garlic & Almond Soup: soups-and-stews/roasted-sweet-garlic-&-almond-soup.md
      - Spinach Tortellini Soup by Joanna Gaines: soups-and-stews/spinach-tortellini-soup-by-joanna-gaines.md
      - Split Pea Soup: soups-and-stews/split-pea-soup.md
  - Vegetarian:
      - Cauliflower Green Bean Mac and Cheese: vegetarian/cauliflower-green-bean-mac-and-cheese.md
      - Creamy Vegan Polenta with Mushrooms and Kale: vegetarian/creamy-vegan-polenta-with-mushrooms-and-kale.md
      - Greens and Grains Bowls: vegetarian/greens-and-grains-bowls.md
      - Fennel and Potato Cassola: vegetarian/fennel-and-potato-cassola.md
      - Game Changers Oat and Lentil Meatloaf: vegetarian/game-changers-oat-and-lentil-meatloaf.md
      - Italian Sausage with Grits & Tomatoes: vegetarian/italian-sausage-with-grits-&-tomatoes.md
      - Lentil Meatballs with Lemon Pesto: vegetarian/lentil-meatballs-with-lemon-pesto.md
      - Meat-Free Meat Loaf: vegetarian/meat-free-meat-loaf.md
      - Mushroom Rice Burgers: vegetarian/mushroom-rice-burgers.md
      - Quinoa and Veggie Power Bowls: vegetarian/quinoa-and-veggie-power-bowls.md
      - Spicy Cashew Quinoa Salad: vegetarian/spicy-cashew-quinoa-salad.md
      - Sprouted Kitchen Lentil & Rice Bowls with Vegetable Kebabs: vegetarian/sprouted-kitchen-lentil-&-rice-bowls-with-vegetable-kebabs.md
      - Texas Potato Pancakes: vegetarian/texas-potato-pancakes.md
      - The Best Began Burger: vegetarian/the-best-vegan-burger.md
      - Vegan Caesar Salad: vegetarian/vegan-caesar-salad.md
      - Vegetable Casserole: vegetarian/vegetable-casserole.md
  - Reference:
      - Equivalents & Substitutes: reference/equivalents-and-substitutes.md
      - Measuring: reference/measuring.md
      - Pressure Cooker: reference/pressure-cooker.md
  - Cooklang Files: "https://github.com/nicholaswilde/recipes/tree/main/cook"
  - Development: development.md
extra:
  social:
    - icon: fontawesome/solid/house
      link: https://nicholaswilde.io/
    - icon: fontawesome/brands/github
      link: https://github.com/nicholaswilde
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/nicholascwilde
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/wildewoodworking/
    - icon: fontawesome/brands/linkedin-in
      link: https://www.linkedin.com/in/nicholaswilde
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/nicholas.wilde/
    - icon: fontawesome/brands/keybase
      link: https://keybase.io/nicholaswilde
    - icon: fontawesome/solid/key
      link: https://github.com/nicholaswilde.gpg

plugins:
  - search
  - minify:
      minify_html: true

markdown_extensions:
  - footnotes
  - attr_list
  - md_in_html
  - admonition
  - tables
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: nicholaswilde
      repo: recipes

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
