---
site_name: Recipes
site_description: A collection of my recipes.
site_author: Nicholas Wilde
site_url: https://nicholaswilde.io/recipes
copyright: Copyright &copy; 2022 Nicholas Wilde
dev_addr: '0.0.0.0:8000'

repo_url: https://github.com/nicholaswilde/recipes
repo_name: nicholaswilde/recipes
edit_uri: "edit/main/docs/"

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
    logo: fontawesome/solid/bowl-rice
  favicon: assets/images/favicon.svg
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.tracking
    #  - navigation.expand
    - navigation.top

nav:
  - Home: index.md
  - Asian:
      - Coconut Curried Vegetables with Rice: asian/coconut-curried-vegetables-with-rice.md
      - Cool and Spicy Noodle Salad: asian/cool-and-spicy-noodle-salad.md
      - Crispy Peanut Tofu & Cauliflower Rice Stir Fry: asian/crispy-peanut-tofu-&-cauliflower-rice-stir-fry.md
      - Everyday Chinese Vegetable Stir-Fry: asian/everyday-chinese-vegetable-stir-fry.md
      - Noodle-Free Pad Thai: asian/noodle-free-pad-thai.md
  - Breakfast:
      - 1-Bowl Carrot Apple Muffins: breakfast/1-bowl-carrot-apple-muffins.md
      - Apple Pie Overnight Oats: breakfast/apple-pie-overnight-oats.md
      - Decadent Chocolate Overnight Oats: breakfast/decadent-chocolate-overnight-oats.md
      - Gordon Ramsay Scrambled Eggs: breakfast/gordon-ramsay-scrambled-eggs.md
      - Joy of Cooking Pancakes: breakfast/joy-of-cooking-pancakes.md
      - The Food Lab Light and Fluffy Scrambled Eggs: breakfast/the-food-lab-light-and-fluffy-scrambled-eggs.md
  - Desserts:
      - 4 Ingredient Chocolate Mousse: desserts/4-ingredient-chocolate-mousse.md
      - Apple Cinnamon Raisin Bars: desserts/apple-cinnamon-raisin-bars.md
      - Best-Ever Banana Bread: desserts/best-ever-banana-bread.md
      - Blueberry Pie: desserts/blueberry-pie.md
      - Buttery Shortbread: desserts/buttery-shortbread.md
      - Chewy Brownies: desserts/chewy-brownies.md
      - Chocolate Chip Peanut Butter Banana Bread: desserts/chocolate-chip-peanut-butter-banana-bread.md
      - Chocolate Scotcheroos: desserts/chocolate-scotcheroos.md
      - Consumer Union Chocolate Chip Cookies: desserts/consumer-union-chocolate-chip-cookies.md
      - Cranberry Orange Bread: desserts/cranberry-orange-bread.md
      - Crème Pâtissière: desserts/crème-pâtissière.md
      - Danish Pastry Dough: desserts/danish-pastry-dough.md
      - Disney's Churros: desserts/disney's-churros.md
      - Disney's Frozen Pineapple Treat: desserts/disney's-frozen-pineapple-treat.md
      - French Fruit Tart: desserts/french-fruit-tart.md
      - Glazed Lemon Bars: desserts/glazed-lemon-bars.md
      - Lemon Blueberry Bread: desserts/lemon-blueberry-bread.md
      - Lemon Pie: desserts/lemon-pie.md
      - Melomakarona: desserts/melomakarona.md
      - Millionaire's Shortbread: desserts/millionaire's-shortbread.md
      - No-Bake Banana and Peanut Butter Caramel Icebox Cake: desserts/no-bake-banana-and-peanut-butter-caramel-icebox-cake.md
      - Oatmeal Chocolate Chip Cookies: desserts/oatmeal-chocolate-chip-cookies.md
      - Pineapple Upside Down Cake: desserts/pineapple-upside-down-cake.md
      - Preposterously Peanut Butter Cup Cookies: desserts/preposterously-peanut-butter-cup-cookies.md
      - Puff Pastry: desserts/puff-pastry.md
      - Slow Cooker Apple Crisp: desserts/slow-cooker-apple-crisp.md
      - Strawberry Mousse: desserts/strawberry-mousse.md
      - Sweet Pastry: desserts/sweet-pastry.md
      - Tollhouse Pie: desserts/tollhouse-pie.md
      - Trader Joe's Key Lime Pie with Strawberry Whipped Cream: desserts/trader-joe's-key-lime-pie-with-strawberry-whipped-cream.md
      - Vegan Chocolate Pudding with Cinnamon and Chile: desserts/vegan-chocolate-pudding-with-cinnamon-and-chile.md
  - Italian:
      - Baked Cream Cheese Spaghetti Casserole: italian/baked-cream-cheese-spaghetti-casserole.md
      - Caprese Risoni: italian/caprese-risoni.md
      - Eggplant Parm Meatballs: italian/eggplant-parm-meatballs.md
      - Eggplant Parmesan Pasta: italian/eggplant-parmesan-pasta.md
      - Ginger Sesame Vegan Meatballs: italian/ginger-sesame-vegan-meatballs.md
      - Healthy Pasta with Pesto and Broccoli: italian/healthy-pasta-with-pesto-and-broccoli.md
      - Light and Tender Potato Gnocchi with Sage Butter Sauce: italian/light-and-tender-potato-gnocchi-with-sage-butter-sauce.md
      - Jamie Oliver Ricotta Fritters: italian/jamie-oliver-ricotta-fritters.md
      - Mezza Luna Lasagna: italian/mezza-luna-lasagna.md
      - Spaghetti Alla Puttanesca: italian/spaghetti-alla-puttanesca.md
      - Spinach Tortellini Soup by Joanna Gaines: italian/spinach-tortellini-soup-by-joanna-gaines.md
      - Summer Pesto Pasta: italian/summer-pesto-pasta.md
      - Trapani-Style Pasta: italian/trapani-style-pasta.md
  - Lunches:
      - Chickpea Sunflower Sandwich: lunches/chickpea-sunflower-sandwich.md
      - Perfect Chickpea Salad: lunches/perfect-chickpea-salad.md
      - Vegan Caesar Salad: lunches/vegan-caesar-salad.md
  - Main:
      - Baked Sweet Potatoes With Chili Beans: main/baked-sweet-potatoes-with-chili-beans.md
      - Cabbage and Sun-Dried Tomato Sauté: main/cabbage-and-sun-dried-tomato-sauté.md
      - Cowboy Quinoa Bake: main/cowboy-quinoa-bake.md
      - Crispy Chicken-less Sliders: main/crispy-chicken-less-sliders.md
      - Fall Turkey Chili With Pumpkin: main/fall-turkey-chili-with-pumpkin.md
      - Fresh Fava Beans with Mint and Scallions: main/fresh-fava-beans-with-mint-and-scallions.md
      - Lemony Lentil Soup: main/lemony-lentil-soup.md
      - Peruvian Burrito Bowl: main/peruvian-burrito-bowl.md
      - Spicy Pumpkin Curry Pot Pie: main/spicy-pumpkin-curry-pot-pie.md
  - Mediterranean:
      - Baked Feta with Chickpeas and Kale: mediterranean/baked-feta-with-chickpeas-and-kale.md
      - Balsamic Lentil Sauté: mediterranean/balsamic-lentil-sauté.md
      - Cook's Illustrated Horiatiki Salata (Greek Salad): mediterranean/cook's-illustrated-horiatiki-salata-(greek-salad).md
      - Gordon Ramsay's Spicy Sausage Rice: mediterranean/gordon-ramsay's-spicy-sausage-rice.md
      - Greek Orzo Stuffed Red Peppers: mediterranean/greek-orzo-stuffed-red-peppers.md
      - Harissa Olive Oil-Braised Chickpeas and Fennel: mediterranean/harissa-olive-oil-braised-chickpeas-and-fennel.md
      - Ikarian Longevity Stew: mediterranean/ikarian-longevity-stew.md
      - Jeanie's Falafel: mediterranean/jeanie's-falafel.md
      - Lemon Garlic Orzo with Roasted Veggies: mediterranean/lemon-garlic-orzo-with-roasted-veggies.md
      - Mediterranean Pasta Salad: mediterranean/mediterranean-pasta-salad.md
      - Saucy Moroccan-Spiced Lentils: mediterranean/saucy-moroccan-spiced-lentils.md
      - Scrambled Chickpea and Spinach Pitas: mediterranean/scrambled-chickpea-and-spinach-pitas.md
      - Sprouted Kitchen Spring Noodles Artichokes and Lemons: mediterranean/sprouted-kitchen-spring-noodles-artichokes-and-lemons.md
      - Tomato Baked White Beans with Lemon Parsley Oil: mediterranean/tomato-baked-white-beans-with-lemon-parsley-oil.md
      - Vegetarian Paella: mediterranean/vegetarian-paella.md
  - Mexican:
      - Black Bean Burritos: mexican/black-bean-burritos.md
      - Cheesy Black Bean Quesadilla Triagles: mexican/cheesy-black-bean-quesadilla-triagles.md
      - Chipotle Breakfast Tacos: mexican/chipotle-breakfast-tacos.md
      - Chipotle Corn Chowder.md: mexican/chipotle-corn-chowder.md
      - Chipotle-Inspired Vegan Burrito Bowls: mexican/chipotle-inspired-vegan-burrito-bowls.md
      - Lentil Fajita Tacos with Zhoug Crema: mexican/lentil-fajita-tacos-with-zhoug-crema.md
      - Mexican Garbanzo Salad: mexican/mexican-garbanzo-salad.md
      - Mexican Lentil Soup: mexican/mexican-lentil-soup.md
      - Potato Tacos: mexican/potato-tacos.md
      - Slow Cooker Black Bean Chili: mexican/slow-cooker-black-bean-chili.md
      - Sweet and Spicy Corncakes: mexican/sweet-and-spicy-corncakes.md
      - Taco Bake: mexican/taco-bake.md
      - Taquito-lada Casserole: mexican/taquito-lada-casserole.md
      - Tofu Tacos: mexican/tofu-tacos.md
  - Pressure Cooker:
      - Black Beans: pressurecooker/black-beans.md
      - Chickpeas: pressurecooker/chickpeas.md
  - Sauces:
      - A Very Popular BBQ Sauce: sauces/a-very-popular-bbq-sauce.md
      - Aji Verde: sauces/aji-verde.md
      - Cashew Chipotle Ranch Dressing: sauces/cashew-chipotle-ranch-dressing.md
      - Classic Mustard: sauces/classic-mustard.md
      - Cook's Country Perfect Pesto: sauces/cook's-country-perfect-pesto.md
      - Lemon-Pepper Parsley Pesto: sauces/lemon-pepper-parsley-pesto.md
      - New York Times' Classic Marinara Sauce: sauces/new-york-times'-classic-marinara-sauce.md
      - Spaghetti Sauce: sauces/spaghetti-sauce.md
      - Special Sauce for Burgers: sauces/special-sauce-for-burgers.md
      - Sweet-and-Spicy Ketchup: sauces/sweet-and-spicy-ketchup.md
      - Tzatziki Sauce: sauces/tzatziki-sauce.md
  - Sides:
      - America's Test Kitchen Best Baked Potatoes: sides/america's-test-kitchen-best-baked-potatoes.md
      - America's Test Kitchen Best Baked Sweet Potatoes: sides/america's-test-kitchen-best-baked-sweet-potatoes.md
      - Eggless Egg Salad: sides/eggless-egg-salad.md
      - Hasselback Roasted Zucchini: sides/hasselback-roasted-zucchini.md
      - Josh Elkin's Mushroom Toast: sides/josh-elkin's-mushroom-toast.md
      - Pickled Red Onions: sides/pickled-red-onions.md
      - Spicy Garlic Edamame: sides/spicy-garlic-edamame.md
      - The Best Crispy Roast Potatoes Ever Recipe: sides/the-best-crispy-roast-potatoes-ever-recipe.md
      - Unexpected Cheddar Cheese Ball: sides/unexpected-cheddar-cheese-ball.md
  - Soups & Stews:
      - Black Bean and Butternut Soup: soups-and-stews/black-bean-and-butternut-soup.md
      - Chickenless Sausage and Lentil Soup: soups-and-stews/chickenless-sausage-and-lentil-soup.md
      - Eggplant Stew: soups-and-stews/eggplant-stew.md
      - Split Pea Soup: soups-and-stews/split-pea-soup.md
  - Vegetarian:
      - Cauliflower Green Bean Mac and Cheese: vegetarian/cauliflower-green-bean-mac-and-cheese.md
      - Greens and Grains Bowls: vegetarian/greens-and-grains-bowls.md
      - Fennel and Potato Cassola: vegetarian/fennel-and-potato-cassola.md
      - Game Changers Oat and Lentil Meatloaf: vegetarian/game-changers-oat-and-lentil-meatloaf.md
      - Meat-Free Meat Loaf: vegetarian/meat-free-meat-loaf.md
      - Quinoa and Veggie Power Bowls: vegetarian/quinoa-and-veggie-power-bowls.md
  - Pressure Cooker: pressure-cooker.md
  - Cooklang Files: "https://github.com/nicholaswilde/recipes/tree/main/cook"
  - Development: development.md
extra:
  social:
    - icon: fontawesome/solid/house
      link: https://nicholaswilde.io/
    - icon: fontawesome/brands/github
      link: https://github.com/nicholaswilde
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/nicholascwilde
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/wildewoodworking/
    - icon: fontawesome/brands/linkedin-in
      link: https://www.linkedin.com/in/nicholaswilde
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/nicholas.wilde/
    - icon: fontawesome/brands/keybase
      link: https://keybase.io/nicholaswilde
    - icon: fontawesome/solid/key
      link: https://github.com/nicholaswilde.gpg

plugins:
  - search
  - minify:
      minify_html: true

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - tables
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: nicholaswilde
      repo: recipes

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
