---

version: '3'

tasks:
  lint:
    desc: Lint the project
    cmds:
      - task: markdownlint
      - task: yamllint
  markdownlint:
    desc: Run markdownlint-cli
    cmds:
      - >-
        docker run --rm -it -v ${PWD}:/markdown:ro
        06kellyjac/markdownlint-cli .
  serve:
    desc: Serve an mkdocs server
    cmds:
      - mkdocs serve
    silent: true
  server:
    desc: Serve a cook server
    cmds:
      - cook server
    silent: true
  yamllint:
    desc: Run yamllint
    cmds:
      - >-
        docker run --rm -it -v ${PWD}:${PWD}:ro -w ${PWD}
        programmerassistant/yamllint yamllint .
  default:
    cmds:
      - task -a
    silent: true
