---

version: '3'

tasks:
  docker-serve:
    desc: Serve an mkdocs server using Docker
    cmds:
      - >-
        docker run --rm -it -p {{ .PORT }}:{{ .PORT}} -v ${PWD}:/docs
        --platform linux/amd64 squidfunk/mkdocs-material serve
        --dev-addr 0.0.0.0:{{ .PORT }} -f ./mkdocs.yml
    vars:
      PORT: 8000
  linkcheck:
    desc: Check for dead links
    cmds:
      - ./scripts/linkcheck.sh
  lint:
    desc: Lint the project
    cmds:
      - task: markdownlint
      - task: yamllint
  list-ingredients:
    desc: List all ingredients in all cook recipes and copy to clipboard.
    cmds:
      - ./scripts/list-ingredients.sh
  markdownlint:
    desc: Run markdownlint-cli
    cmds:
      - >-
        docker run --rm -it -v ${PWD}:/markdown:ro
        06kellyjac/markdownlint-cli .
  markdownlint-fix:
    desc: Run markdownlint-cli fix
    cmds:
      - >-
        docker run --rm -it -v ${PWD}:/markdown:ro
        06kellyjac/markdownlint-cli -f .
  serve:
    desc: Serve an mkdocs server
    cmds:
      - mkdocs serve
    silent: true
  server:
    desc: Serve a cook server
    cmds:
      - cook server
    silent: true
  yamllint:
    desc: Run yamllint
    cmds:
      - >-
        docker run --rm -it -v ${PWD}:${PWD}:ro -w ${PWD}
        programmerassistant/yamllint yamllint .
  default:
    cmds:
      - task -a
    silent: true
