---
name: spellcheck
on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  spellcheck:
    name: spellcheck
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup npm
        uses: actions/setup-node@v3
      - name: Setup spellchecker
        run: npm install --location=global spellchecker-cli
      - run: npm list --global spellchecker-cli
      - name: Run spellcheck
        run: ./scripts/spellcheck.sh
